### ISSUE TITLE
Windows build fails

### ISSUE THREAD

**Issue by kripken** [emscripten-ports/libpng#1]
This port uses configure, which is not functional on windows systems by default.

It would be more portable to avoid configure and just bundle the output of configure, if that is possible. I believe we do this for other ports.

**Comment by kripken** [comment]
Emscripten bot error: http://clb.demon.fi:8112/builders/win-incoming/builds/825/steps/Tests-other/logs/stdio

**Comment by nadult** [comment]
Actually, no (please look into the log file). Configure is used when building zlib. libpng is built without any external scripts (configure or cmake-generated) or makefiles, everything is in the python script.

**Comment by nadult** [comment]
Still, I can try and fix zlib. That should be easy :)

**Comment by nadult** [comment]
This patch should fix the problem:
https://github.com/nadult/emscripten/commit/3defd27ff82e65bab1ee04ce4c69964f4fc6fbbe

**Comment by kripken** [comment]
Thanks! And sorry for misattributing the blame here ;)

Were you planning to create a pull with that change? If not I can pick it up.

**Comment by nadult** [comment]
NP :) You can pick it up. I've tested it on linux only though (but it should be working on Windows as well).

**Comment by kripken** [comment]
Thanks, edited a little and pushed to emscripten incoming as https://github.com/kripken/emscripten/commit/2757b961386105c17d6a142a665f32c0c47c9a0d .
