### ISSUE TITLE
README should explain why this repo exists?

### ISSUE THREAD

**Issue by edmund-huber** [emscripten-ports/libpng#7]
Hello there! I'm a new emscripten user. I'm here because I attempted to `#include <libpng.h>`, figuring that `emcc` would simply find and compile my system libpng. It seems that instead I'm supposed to use the libpng port (this repo).

But I don't see why this port/repo exists. The tip of the default branch is `918d23f658cb31e6db539ee0411d212408a9fcea`, which is a commit in the libpng upstream (https://github.com/glennrp/libpng). So it seems there are no changes from upstream? Why not point to a sha/tag in the libpng upstream instead?

**Comment by kripken** [comment]
It's possible this repo is not needed, yes. In general we create a mirror repo when we either have local patches that we can't get upstreamed, or if upstream is not on github (as we've had issues with downloads from other sites). I don't remember the specific history with this library, but if the repo is not needed then let's remove it. A PR to do that in emscripten would be welcome, and after that I can delete this repo.

**Comment by edmund-huber** [comment]
Yeah, I think "the upstream might move" and/or "the upstream isn't an actual git repo" (as is the case of zlib) is a good enough rationale. Thanks!
